name: AutoRunner
on:
  workflow_dispatch:
  schedule:
    - cron: '32 04 * * *'

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Test automation
        run: echo "Workflow triggered successfully at $(date)"
